"""PHASE 43 — CRM operator mode tests.

Covers:
  AI READ  — call list, overdue follow-ups, pipeline summary, lead
             lookup, lead timeline
  AI WRITE — move stage, create activity, internal note, assign
             salesperson, pause/resume, mark Won/Lost, tags
  SECURITY — ACL scope (AI cannot touch leads outside the acting user's
             record rules), no arbitrary models / ORM commands, audit
             notes are internal (mt_note, never emailed), no customer
             email generated by audit logging.
"""
import json

from odoo.exceptions import AccessError, UserError
from odoo.tests.common import TransactionCase

from odoo.addons.prema_ai_auditor.services import crm_operator


class TestCrmOperatorBase(TransactionCase):
    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.Lead = cls.env['crm.lead']
        cls.Stage = cls.env['crm.stage']
        cls.admin = cls.env.ref('base.user_admin')
        # canonical stages (xmlid resolution like the service uses)
        cls.st_new = cls.env.ref('premafirm_ai_engine.crm_stage_new_uncontacted')
        cls.st_outreach = cls.env.ref('premafirm_ai_engine.crm_stage_outreach_sent')
        cls.st_engaged = cls.env.ref('premafirm_ai_engine.crm_stage_engaged_replied')
        cls.st_onboarding = cls.env.ref('premafirm_ai_engine.crm_stage_onboarding')
        cls.st_paused = cls.env.ref('premafirm_ai_engine.crm_stage_paused')
        cls.st_lost = cls.env.ref('premafirm_ai_engine.crm_stage_lost')
        cls.call_type = cls.env['mail.activity.type'].search(
            [('name', '=', 'Call')], limit=1)

    def _make_lead(self, name='Fixture Co', **kw):
        vals = {
            'name': name,
            'type': 'opportunity',
            'stage_id': self.st_outreach.id,
            'user_id': self.admin.id,
        }
        vals.update(kw)
        return self.Lead.create(vals)


class TestCrmOperatorRead(TestCrmOperatorBase):

    def test_call_list_prioritizes_overdue_calls(self):
        lead_a = self._make_lead('Alpha Foods', partner_name='Alpha Foods')
        lead_b = self._make_lead('Beta Distributors', partner_name='Beta Distributors',
                                 stage_id=self.st_engaged.id)
        # overdue call on A (today - 3), call due today on B
        self.env['mail.activity'].create({
            'activity_type_id': self.call_type.id,
            'res_id': lead_a.id,
            'res_model_id': self.env['ir.model']._get_id('crm.lead'),
            'user_id': self.admin.id,
            'summary': 'Call Alpha',
            'date_deadline': '2020-01-01',
        })
        self.env['mail.activity'].create({
            'activity_type_id': self.call_type.id,
            'res_id': lead_b.id,
            'res_model_id': self.env['ir.model']._get_id('crm.lead'),
            'user_id': self.admin.id,
            'summary': 'Call Beta',
            'date_deadline': '2020-01-01',
        })
        out = crm_operator.op_get_call_list(self.env)
        self.assertGreaterEqual(out['count'], 2)
        # overdue-first ordering
        companies = [c['company'] for c in out['call_list']]
        self.assertEqual(companies[0], 'Alpha Foods')

    def test_overdue_activities(self):
        lead = self._make_lead('Overdue Co')
        self.env['mail.activity'].create({
            'activity_type_id': self.call_type.id,
            'res_id': lead.id,
            'res_model_id': self.env['ir.model']._get_id('crm.lead'),
            'user_id': self.admin.id,
            'summary': 'Overdue call',
            'date_deadline': '2020-01-01',
        })
        out = crm_operator.op_get_overdue_activities(self.env)
        self.assertGreaterEqual(out['count'], 1)
        self.assertEqual(out['overdue'][0]['lead_id'], lead.id)

    def test_pipeline_summary(self):
        out = crm_operator.op_get_pipeline_summary(self.env)
        names = [s['stage'] for s in out['pipeline']]
        self.assertIn('OUTREACH SENT', names)
        self.assertNotIn('New', names)  # legacy folded stage not listed

    def test_lead_lookup_and_timeline(self):
        lead = self._make_lead('Lookup Co')
        lead.message_post(body='Hello from customer', subtype_xmlid='mail.mt_comment')
        found = crm_operator.op_search_leads(self.env, 'Lookup Co')
        self.assertEqual(found['count'], 1)
        got = crm_operator.op_get_lead(self.env, lead.id)
        self.assertEqual(got['lead']['name'], 'Lookup Co')
        tl = crm_operator.op_get_lead_timeline(self.env, lead.id)
        self.assertGreaterEqual(len(tl['entries']), 1)

    def test_stage_leads_filters_canonical_only(self):
        lead = self._make_lead('Stage Co')
        out = crm_operator.op_get_stage_leads(self.env, 'onboarding')
        # fixture is in outreach, not onboarding
        self.assertNotIn(lead.id, [l['id'] for l in out['leads']])
        out2 = crm_operator.op_get_stage_leads(self.env, 'outreach')
        self.assertIn(lead.id, [l['id'] for l in out2['leads']])

    def test_legacy_stage_name_never_resolves(self):
        stage, canonical = crm_operator.resolve_stage(self.env, 'Call Back')
        self.assertFalse(canonical, 'legacy stage must not resolve')
        stage, canonical = crm_operator.resolve_stage(self.env, 'New')
        self.assertEqual(canonical, 'NEW / UNCONTACTED')

    def test_lead_resolution_dedupes_exact_and_fuzzy(self):
        """Regression: 'exact + fuzzy' produced [370, 370] and a single
        match looked ambiguous. '|' union must dedupe."""
        lead = self._make_lead('Dedupe Co')
        lead.partner_name = 'Dedupe Co'
        session = self.env['prema.ai.session'].create({'name': 'Dedupe'})
        ids, ambiguous = session._resolve_lead_ids(['Dedupe Co'])
        self.assertEqual(ids, [lead.id])
        self.assertFalse(ambiguous)

    def test_dispatch_read_ignores_unexpected_router_kwargs(self):
        """Regression: the LLM router emitted activity_word for a call
        list request and op_get_call_list crashed on the unexpected
        kwarg. dispatch must pass only accepted kwargs."""
        self._make_lead('Kwarg Co')
        res = crm_operator.dispatch(self.env, 'get_call_list',
                                    {'activity_word': 'Call'})
        self.assertEqual(res['kind'], 'read')
        self.assertIn('call_list', res['result'])


class TestCrmOperatorWrite(TestCrmOperatorBase):

    def test_move_lead_stage_audited(self):
        lead = self._make_lead('Move Co')
        res = crm_operator.op_move_lead_stage(
            self.env, lead.id, 'onboarding', request_text='move to onboarding')
        self.assertEqual(res['status'], 'done')
        self.assertEqual(res['to'], 'ONBOARDING')
        self.assertEqual(lead.stage_id, self.st_onboarding)
        # audit log + internal chatter note
        logs = self.env['prema.ai.crm.action'].search(
            [('lead_id', '=', lead.id), ('action', '=', 'move_lead_stage')])
        self.assertEqual(len(logs), 1)
        self.assertEqual(logs.old_value, 'OUTREACH SENT')
        self.assertEqual(logs.new_value, 'ONBOARDING')
        notes = lead.message_ids.filtered(
            lambda m: m.subtype_id == self.env.ref('mail.mt_note'))
        self.assertTrue(any('Prema AI moved' in (n.body or '') for n in notes))
        # no email subtype on the audit note
        self.assertFalse(notes.filtered(
            lambda m: m.message_type == 'email'))

    def test_move_to_won_requires_mark_won(self):
        lead = self._make_lead('Won Co')
        with self.assertRaises(UserError):
            crm_operator.op_move_lead_stage(self.env, lead.id, 'won')

    def test_mark_won_single_lead_previews_until_confirmed(self):
        """Spec (7): Won/Lost are NOT reversible → high-impact → even a
        single-record mark won returns a preview first."""
        lead = self._make_lead('WonGate Co')
        res = crm_operator.dispatch(self.env, 'mark_won',
                                    {'lead_ids': [lead.id],
                                     'request_text': 'mark won'})
        self.assertEqual(res['kind'], 'preview')
        self.assertTrue(lead.active)
        self.assertNotEqual(lead.stage_id.name, 'WON / ACTIVE CUSTOMER')
        res2 = crm_operator.dispatch(self.env, 'mark_won',
                                     {'lead_ids': [lead.id],
                                      'request_text': 'mark won',
                                      'confirm': True})
        self.assertEqual(res2['kind'], 'write')
        self.assertEqual(lead.stage_id.name, 'WON / ACTIVE CUSTOMER')

    def test_fallback_note_to_lead_resolves_single(self):
        """Regression: the LLM router repeatedly refused 'Add an internal
        note to Gobolt: ...' as a CRM request and the note was misrouted
        to lead-creation. The rule-based fallback must parse it as an
        add_internal_note write on exactly one lead."""
        # unique name — the live DB already has a lead named 'Gobolt',
        # and the fallback must never resolve an ambiguous name
        lead = self._make_lead('FallbackGobolt Test Co')
        session = self.env['prema.ai.session'].create({'name': 'Fallback'})
        parsed = session._crm_fallback_intent(
            'Add an internal note to FallbackGobolt Test Co: '
            'Prema AI live UAT test note')
        self.assertEqual(parsed['intent'], 'add_internal_note')
        self.assertIn('Prema AI live UAT test note', parsed['note'])
        self.assertEqual(parsed['lead_query'], 'FallbackGobolt Test Co')

    def test_fallback_move_to_canonical_stage(self):
        lead = self._make_lead('MoveFallback Co')
        session = self.env['prema.ai.session'].create({'name': 'FallbackM'})
        parsed = session._crm_fallback_intent(
            'Move lead MoveFallback Co to onboarding')
        self.assertEqual(parsed['intent'], 'move_lead_stage')
        self.assertEqual(parsed['stage_name'], 'ONBOARDING')
        self.assertEqual(parsed['lead_query'], 'MoveFallback Co')

    def test_fallback_call_activity_and_deadline(self):
        lead = self._make_lead('CallFallback Co')
        session = self.env['prema.ai.session'].create({'name': 'FallbackC'})
        parsed = session._crm_fallback_intent(
            'Create a Call activity on CallFallback Co for tomorrow morning')
        self.assertEqual(parsed['intent'], 'create_activity')
        self.assertEqual(parsed['activity_word'], 'Call')
        self.assertEqual(parsed['lead_query'], 'CallFallback Co')

    def test_fallback_mark_won_and_never_ambiguous(self):
        """The fallback must never guess: two matching leads -> None."""
        self._make_lead('Ambiguo Co')
        self._make_lead('Ambiguo Co')
        session = self.env['prema.ai.session'].create({'name': 'FallbackA'})
        parsed = session._crm_fallback_intent('Mark Ambiguo Co as won')
        self.assertIsNone(parsed, 'ambiguous lead must not resolve')

    def test_fallback_ignores_non_crm_chat(self):
        session = self.env['prema.ai.session'].create({'name': 'FallbackN'})
        parsed = session._crm_fallback_intent('What is the weather like?')
        self.assertIsNone(parsed)

    def test_fallback_write_flows_through_dispatch_and_audits(self):
        """Regression for the live failure: LLM router refuses the request
        (is_crm_operator=false) → the fallback must take over. Since the
        2026-08-31 preview-every-write decision the write PREVIEWS first;
        an explicit 'confirm' then executes it through dispatch(), where
        ACL + audit log apply."""
        from unittest import mock
        lead = self._make_lead('AuditFallback Co')
        session = self.env['prema.ai.session'].create({'name': 'FallbackD'})
        with mock.patch.object(
                session.__class__, '_call_responses_text',
                return_value='{"is_crm_operator": false}'):
            reply = session._handle_crm_operator_request(
                'Add an internal note to AuditFallback Co: spoke with John')
        self.assertIsInstance(reply, str)
        self.assertIn('AuditFallback Co', reply)
        # preview only — nothing applied, nothing audited yet
        self.assertTrue(session.crm_pending_preview)
        self.assertEqual(self.env['prema.ai.crm.action'].search_count(
            [('lead_id', '=', lead.id),
             ('action', '=', 'add_internal_note')]), 0)
        self.assertFalse(any('spoke with John' in (m.body or '')
                             for m in lead.message_ids))
        # explicit confirmation executes the write + audit
        result = session.send_message('confirm')
        self.assertIsInstance(result, dict)
        self.assertEqual(self.env['prema.ai.crm.action'].search_count(
            [('lead_id', '=', lead.id),
             ('action', '=', 'add_internal_note')]), 1)
        notes = lead.message_ids.filtered(
            lambda m: m.subtype_id == self.env.ref('mail.mt_note'))
        self.assertTrue(any('spoke with John' in (n.body or '') for n in notes))
        self.assertFalse(session.crm_pending_preview)

    def test_chat_confirms_pending_preview_without_keywords(self):
        """Regression: 'yes, go ahead' contains no CRM keyword, so the
        keyword gate skipped the operator handler and the LLM only wrote
        a confirmation-style reply — nothing executed. A pending preview
        must force the operator path, and 'go ahead' must execute it."""
        lead = self._make_lead('Confirm Co')
        session = self.env['prema.ai.session'].create({'name': 'Confirm'})
        session.crm_pending_preview = json.dumps({
            'intent': 'mark_won',
            'params': {'lead_ids': [lead.id], 'request_text': 'mark won'},
        })
        reply = session.send_message('yes, go ahead')
        # send_message returns {'reply': str, 'pending_action': ...}
        self.assertIn('WON', reply['reply'])
        self.assertEqual(lead.stage_id.name, 'WON / ACTIVE CUSTOMER')
        logs = self.env['prema.ai.crm.action'].search(
            [('lead_id', '=', lead.id), ('action', '=', 'mark_won')])
        self.assertEqual(len(logs), 1)
        self.assertFalse(session.crm_pending_preview)

    def test_create_call_activity(self):
        lead = self._make_lead('Call Co')
        res = crm_operator.op_create_activity(
            self.env, lead.id, activity_word='call',
            summary='Call John re pricing',
            date_deadline='2026-08-21',
            request_text='call him tomorrow morning')
        self.assertEqual(res['status'], 'done')
        act = self.env['mail.activity'].browse(res['activity_id'])
        self.assertEqual(act.activity_type_id, self.call_type)
        self.assertEqual(act.res_id, lead.id)

    def test_add_internal_note_never_emails(self):
        lead = self._make_lead('Note Co')
        crm_operator.op_add_internal_note(
            self.env, lead.id, 'Spoke with John — wants pricing Friday',
            request_text='add a note')
        notes = lead.message_ids.filtered(
            lambda m: m.subtype_id == self.env.ref('mail.mt_note'))
        self.assertTrue(any('pricing Friday' in (n.body or '') for n in notes))
        self.assertFalse(notes.filtered(lambda m: m.message_type == 'email'))

    def test_assign_salesperson(self):
        lead = self._make_lead('Assign Co', user_id=False)
        res = crm_operator.op_assign_salesperson(
            self.env, lead.id, self.admin.name, request_text='assign to admin')
        self.assertEqual(res['status'], 'done')
        self.assertEqual(lead.user_id, self.admin)
        self.assertEqual(res['from'], 'unassigned')

    def test_pause_resume_restores_previous_stage(self):
        lead = self._make_lead('Pause Co', stage_id=self.st_onboarding.id)
        p = crm_operator.op_pause_lead(self.env, lead.id,
                                       request_text='pause until next month')
        self.assertEqual(p['status'], 'done')
        self.assertEqual(lead.stage_id, self.st_paused)
        r = crm_operator.op_resume_lead(self.env, lead.id,
                                        request_text='resume')
        self.assertEqual(r['status'], 'done')
        self.assertEqual(lead.stage_id, self.st_onboarding,
                         'resume must restore the pre-pause stage')

    def test_mark_won_and_lost(self):
        lead_w = self._make_lead('WonCo')
        w = crm_operator.op_mark_won(self.env, lead_w.id,
                                     request_text='mark as won')
        self.assertEqual(w['status'], 'done')
        self.assertTrue(lead_w.active)
        lead_l = self._make_lead('LostCo')
        l = crm_operator.op_mark_lost(self.env, lead_l.id, reason='pricing',
                                      request_text='mark lost')
        self.assertEqual(l['status'], 'done')
        self.assertEqual(lead_l.stage_id, self.st_lost)

    def test_add_remove_tag(self):
        lead = self._make_lead('Tag Co')
        add = crm_operator.op_add_tag(self.env, lead.id, 'Retail',
                                      request_text='add Retail tag')
        self.assertEqual(add['status'], 'done')
        self.assertIn('Retail', [t.name for t in lead.tag_ids])
        rm = crm_operator.op_remove_tag(self.env, lead.id, 'Retail',
                                        request_text='remove tag')
        self.assertEqual(rm['status'], 'done')
        self.assertNotIn('Retail', [t.name for t in lead.tag_ids])

    def test_single_write_previews_until_confirmed(self):
        """2026-08-31 decision: EVERY write previews first — even a single
        reversible stage move no longer executes immediately."""
        lead = self._make_lead('SinglePreview Co')
        params = {'lead_ids': [lead.id], 'stage_name': 'onboarding',
                  'request_text': 'move to onboarding'}
        res = crm_operator.dispatch(self.env, 'move_lead_stage', params)
        self.assertEqual(res['kind'], 'preview')
        self.assertEqual(lead.stage_id, self.st_outreach)
        self.assertEqual(self.env['prema.ai.crm.action'].search_count(
            [('lead_id', '=', lead.id)]), 0)
        params['confirm'] = True
        res2 = crm_operator.dispatch(self.env, 'move_lead_stage', params)
        self.assertEqual(res2['kind'], 'write')
        self.assertEqual(lead.stage_id, self.st_onboarding)
        self.assertEqual(self.env['prema.ai.crm.action'].search_count(
            [('lead_id', '=', lead.id)]), 1)

    def test_bulk_move_previews_then_confirms(self):
        leads = [self._make_lead('Bulk%d Co' % i) for i in range(3)]
        params = {'lead_ids': [l.id for l in leads],
                  'stage_name': 'quote sent'}
        res = crm_operator.dispatch(self.env, 'move_lead_stage', params)
        self.assertEqual(res['kind'], 'preview')
        for l in leads:
            self.assertNotEqual(l.stage_id.name, 'QUOTE SENT')
        params['confirm'] = True
        res2 = crm_operator.dispatch(self.env, 'move_lead_stage', params)
        self.assertEqual(res2['kind'], 'write')
        for l in leads:
            self.assertEqual(l.stage_id.name, 'QUOTE SENT')


class TestCrmOperatorSecurity(TestCrmOperatorBase):
    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.limited = cls.env['res.users'].create({
            'name': 'CRM Portal-ish User',
            'login': 'crm_limited_%s' % cls.id,
            'groups_id': [(6, 0, [
                cls.env.ref('base.group_user').id,
            ])],
        })
        # restrict this user with a record rule: only leads they own
        cls.env['ir.rule'].create({
            'name': 'Test rule: own leads only',
            'model_id': cls.env.ref('crm.model_crm_lead').id,
            'domain_force': "[('user_id', '=', user.id)]",
            'groups': [(6, 0, [cls.env.ref('base.group_user').id])],
        })

    def test_ai_cannot_touch_lead_outside_user_scope(self):
        admin_lead = self._make_lead('Admin Only Co', user_id=self.admin.id)
        other_env = self.env(user=self.limited.id)
        # read blocked by record rule
        with self.assertRaises(AccessError):
            crm_operator.op_get_lead(other_env, admin_lead.id)
        # write blocked too
        with self.assertRaises(AccessError):
            crm_operator.op_move_lead_stage(
                other_env, admin_lead.id, 'onboarding',
                request_text='move')
        # a lead owned by the limited user is writable
        mine = self._make_lead('Mine Co', user_id=self.limited.id)
        res = crm_operator.op_move_lead_stage(
            other_env, mine.id, 'onboarding', request_text='move mine')
        self.assertEqual(res['status'], 'done')

    def test_dispatch_rejects_unknown_intents(self):
        with self.assertRaises(UserError):
            crm_operator.dispatch(self.env, 'exec_any_python',
                                  {'lead_ids': [1]})

    def test_update_lead_whitelist(self):
        lead = self._make_lead('Whitelist Co')
        with self.assertRaises(UserError):
            crm_operator.op_update_lead(
                self.env, lead.id, {'stage_id': self.st_onboarding.id})
        res = crm_operator.op_update_lead(
            self.env, lead.id, {'expected_revenue': 50000})
        self.assertEqual(res['status'], 'done')
        self.assertEqual(lead.expected_revenue, 50000)

    def test_audit_log_has_no_unlink(self):
        """TransactionCase env is superuser — ACLs bypassed there. Use a
        plain internal user so the audit table's ACL really applies."""
        uenv = self.env(user=self.limited.id)
        uenv['prema.ai.crm.action'].check_access_rights('read')
        uenv['prema.ai.crm.action'].check_access_rights('create')
        uenv['prema.ai.crm.action'].check_access_rights('write')
        with self.assertRaises(AccessError):
            uenv['prema.ai.crm.action'].check_access_rights('unlink')

    def test_chat_created_leads_land_in_canonical_new(self):
        """_new_stage_id must resolve NEW / UNCONTACTED, never the
        folded legacy 'New'."""
        session = self.env['prema.ai.session'].create({
            'name': 'Test session',
        })
        stage_id = session._new_stage_id()
        stage = self.env['crm.stage'].browse(stage_id)
        self.assertEqual(stage.name, 'NEW / UNCONTACTED')
        self.assertFalse(stage.fold)

    def test_no_customer_email_from_audit_logging(self):
        """Audit chatter notes are internal; completing the flow must
        not create outgoing mail.mail records."""
        lead = self._make_lead('Email Safe Co')
        crm_operator.op_move_lead_stage(self.env, lead.id, 'negotiation',
                                        request_text='move')
        mail_count = self.env['mail.mail'].search_count([
            ('model', '=', 'crm.lead'), ('res_id', '=', lead.id)])
        self.assertEqual(mail_count, 0)
