server {
    listen 80;
    server_name erp.premafirm.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name erp.premafirm.com;

    ssl_certificate     /etc/letsencrypt/live/erp.premafirm.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/erp.premafirm.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    access_log /var/log/nginx/erp_access.log;
    error_log  /var/log/nginx/erp_error.log;

    proxy_read_timeout 720s;
    proxy_connect_timeout 720s;
    proxy_send_timeout 720s;

    proxy_set_header X-Forwarded-Host  $host;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP         $remote_addr;

    location /longpolling { proxy_pass http://odoochat; }
    location /           { proxy_pass http://odoo; proxy_redirect off; }

    gzip on;
    gzip_types text/css text/scss text/plain text/xml application/xml application/json application/javascript;
}
