# Upstreams
upstream odoo {
    server 127.0.0.1:8069;
}
upstream odoochat {
    server 127.0.0.1:8072;
}

# Redirect HTTP -> HTTPS
server {
    if ($host = www.premafirm.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = premafirm.com) {
        return 301 https://www.$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name premafirm.com  www.premafirm.com;
    return 301 https://$host$request_uri;
}

# Main HTTPS Server
server {
    listen 443 ssl;
    server_name premafirm.com  www.premafirm.com;

    # SSL certs (Certbot)
    ssl_certificate /etc/letsencrypt/live/www.premafirm.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/www.premafirm.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # Proxy settings
    proxy_read_timeout 720s;
    proxy_connect_timeout 720s;
    proxy_send_timeout 720s;

    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;

    # Logs
    access_log /var/log/nginx/odoo.access.log;
    error_log /var/log/nginx/odoo.error.log;

    # Longpolling
    location /longpolling {
        proxy_pass http://odoochat;
    }

    # Gzip
    gzip_types text/css text/scss text/plain text/xml application/xml application/json application/javascript;
    gzip on;

    # Main Odoo backend
    location / {
        proxy_pass http://odoo;
        proxy_redirect off;
    }

}
