                    name                    | latest_version |   state   
--------------------------------------------+----------------+-----------
 account                                    | 18.0.1.3       | installed
 account_accountant                         | 18.0.1.1       | installed
 account_accountant_fleet                   | 18.0.1.0       | installed
 account_asset                              | 18.0.1.0       | installed
 account_asset_fleet                        | 18.0.1.0       | installed
 account_auto_transfer                      | 18.0.1.0       | installed
 account_avatax                             | 18.0.1.0       | installed
 account_avatax_sale                        | 18.0.1.0       | installed
 account_avatax_stock                       | 18.0.1.0       | installed
 account_bank_statement_extract             | 18.0.1.0       | installed
 account_bank_statement_import              | 18.0.1.0       | installed
 account_bank_statement_import_camt         | 18.0.1.0       | installed
 account_bank_statement_import_csv          | 18.0.1.0       | installed
 account_bank_statement_import_ofx          | 18.0.1.0       | installed
 account_base_import                        | 18.0.1.0       | installed
 account_budget                             | 18.0.1.0       | installed
 account_disallowed_expenses                | 18.0.1.0       | installed
 account_disallowed_expenses_fleet          | 18.0.1.0       | installed
 account_edi_ubl_cii                        | 18.0.1.0       | installed
 account_external_tax                       | 18.0.1.0       | installed
 account_extract                            | 18.0.1.0       | installed
 account_fleet                              | 18.0.1.0       | installed
 account_followup                           | 18.0.1.1       | installed
 account_invoice_extract                    | 18.0.1.0       | installed
 account_invoice_extract_purchase           | 18.0.1.0       | installed
 account_loans                              | 18.0.1.0       | installed
 account_online_synchronization             | 18.0.1.0       | installed
 account_payment                            | 18.0.2.0       | installed
 account_qr_code_sepa                       | 18.0.0.1       | installed
 account_reports                            | 18.0.1.0       | installed
 account_reports_cash_basis                 | 18.0.1.0       | installed
 accountant                                 | 18.0.1.1       | installed
 analytic                                   | 18.0.1.2       | installed
 analytic_enterprise                        | 18.0.0.1       | installed
 attachment_indexation                      | 18.0.2.1       | installed
 auth_signup                                | 18.0.1.0       | installed
 auth_totp                                  | 18.0.1.0       | installed
 auth_totp_mail                             | 18.0.1.0       | installed
 auth_totp_portal                           | 18.0.1.0       | installed
 auto_database_backup                       | 18.0.2.0.1     | installed
 barcodes                                   | 18.0.2.0       | installed
 barcodes_gs1_nomenclature                  | 18.0.1.0       | installed
 base                                       | 18.0.1.3       | installed
 base_automation                            | 18.0.1.0       | installed
 base_automation_hr_contract                | 18.0.1.0       | installed
 base_iban                                  | 18.0.1.0       | installed
 base_import                                | 18.0.2.0       | installed
 base_import_module                         | 18.0.1.0       | installed
 base_install_request                       | 18.0.1.0       | installed
 base_setup                                 | 18.0.1.0       | installed
 bus                                        | 18.0.1.0       | installed
 calendar                                   | 18.0.1.1       | installed
 calendar_sms                               | 18.0.1.1       | installed
 contacts                                   | 18.0.1.0       | installed
 contacts_enterprise                        | 18.0.1.0       | installed
 crm                                        | 18.0.1.8       | installed
 crm_enterprise                             | 18.0.1.0       | installed
 crm_helpdesk                               | 18.0.1.1       | installed
 crm_iap_enrich                             | 18.0.1.1       | installed
 crm_iap_mine                               | 18.0.1.2       | installed
 crm_sms                                    | 18.0.1.1       | installed
 currency_rate_live                         | 18.0.1.0       | installed
 digest                                     | 18.0.1.1       | installed
 digest_enterprise                          | 18.0.1.0       | installed
 documents                                  | 18.0.1.4       | installed
 documents_account                          | 18.0.1.0       | installed
 documents_fleet                            | 18.0.1.0       | installed
 documents_hr                               | 18.0.1.0       | installed
 documents_hr_contract                      | 18.0.1.0       | installed
 documents_hr_expense                       | 18.0.1.0       | installed
 documents_hr_recruitment                   | 18.0.1.0       | installed
 documents_product                          | 18.0.1.0       | installed
 documents_project                          | 18.0.1.0       | installed
 documents_project_sale                     | 18.0.1.0       | installed
 documents_spreadsheet                      | 18.0.1.0       | installed
 fleet                                      | 18.0.0.1       | installed
 google_recaptcha                           | 18.0.1.0       | installed
 helpdesk                                   | 18.0.1.6       | installed
 helpdesk_sale                              | 18.0.1.0       | installed
 helpdesk_sms                               | 18.0.1.0       | installed
 hr                                         | 18.0.1.1       | installed
 hr_calendar                                | 18.0.1.0       | installed
 hr_contract                                | 18.0.1.0       | installed
 hr_contract_reports                        | 18.0.1.0       | installed
 hr_expense                                 | 18.0.2.0       | installed
 hr_expense_extract                         | 18.0.1.0       | installed
 hr_expense_predict_product                 | 18.0.1.0       | installed
 hr_fleet                                   | 18.0.1.0       | installed
 hr_gantt                                   | 18.0.1.0       | installed
 hr_hourly_cost                             | 18.0.1.0       | installed
 hr_mobile                                  | 18.0.1.0       | installed
 hr_org_chart                               | 18.0.1.0       | installed
 hr_recruitment                             | 18.0.1.1       | installed
 hr_recruitment_extract                     | 18.0.1.0       | installed
 hr_recruitment_reports                     | 18.0.1.0       | installed
 hr_recruitment_skills                      | 18.0.1.0       | installed
 hr_recruitment_sms                         | 18.0.1.0       | installed
 hr_skills                                  | 18.0.1.0       | installed
 hr_timesheet                               | 18.0.1.0       | installed
 html_editor                                | 18.0.1.0       | installed
 http_routing                               | 18.0.1.0       | installed
 iap                                        | 18.0.1.1       | installed
 iap_crm                                    | 18.0.1.0       | installed
 iap_extract                                | 18.0.1.0       | installed
 iap_mail                                   | 18.0.1.0       | installed
 l10n_ca                                    | 18.0.1.1       | installed
 l10n_ca_reports                            | 18.0.1.0       | installed
 link_tracker                               | 18.0.1.1       | installed
 mail                                       | 18.0.1.18      | installed
 mail_bot                                   | 18.0.1.2       | installed
 mail_bot_hr                                | 18.0.1.0       | installed
 mail_enterprise                            | 18.0.1.0       | installed
 mail_mobile                                | 18.0.1.1       | installed
 marketing_automation                       | 18.0.1.0       | installed
 marketing_automation_crm                   | 18.0.1.0       | installed
 marketing_automation_whatsapp              | 18.0.1.0       | installed
 mass_mailing                               | 18.0.2.7       | installed
 mass_mailing_crm                           | 18.0.1.0       | installed
 mass_mailing_sale                          | 18.0.1.0       | installed
 mass_mailing_themes                        | 18.0.1.2       | installed
 mrp                                        | 18.0.2.0       | installed
 mrp_account                                | 18.0.1.0       | installed
 mrp_account_enterprise                     | 18.0.1.0       | installed
 mrp_accountant                             | 18.0.1.0       | installed
 mrp_plm                                    | 18.0.1.0       | installed
 mrp_workorder                              | 18.0.1.0       | installed
 mrp_workorder_hr_account                   | 18.0.1.0       | installed
 mrp_workorder_plm                          | 18.0.1.0       | installed
 onboarding                                 | 18.0.1.2       | installed
 partner_autocomplete                       | 18.0.1.1       | installed
 payment                                    | 18.0.2.0       | installed
 phone_validation                           | 18.0.2.1       | installed
 portal                                     | 18.0.1.0       | installed
 portal_rating                              | 18.0.1.0       | installed
 premafirm_ai_engine                        | 18.0.2.0.0     | installed
 privacy_lookup                             | 18.0.1.0       | installed
 product                                    | 18.0.1.2       | installed
 product_barcodelookup                      | 18.0.1.0       | installed
 project                                    | 18.0.1.3       | installed
 project_account                            | 18.0.1.0       | installed
 project_account_asset                      | 18.0.1.0       | installed
 project_account_budget                     | 18.0.1.0       | installed
 project_enterprise                         | 18.0.1.0       | installed
 project_enterprise_hr                      | 18.0.1.0       | installed
 project_enterprise_hr_contract             | 18.0.1.0       | installed
 project_enterprise_hr_skills               | 18.0.1.0       | installed
 project_helpdesk                           | 18.0.1.0       | installed
 project_hr_expense                         | 18.0.1.0       | installed
 project_hr_skills                          | 18.0.1.0       | installed
 project_mrp                                | 18.0.1.0       | installed
 project_mrp_account                        | 18.0.1.0       | installed
 project_mrp_sale                           | 18.0.1.0       | installed
 project_mrp_workorder_account              | 18.0.1.0       | installed
 project_purchase                           | 18.0.1.0       | installed
 project_purchase_stock                     | 18.0.1.0       | installed
 project_sale_expense                       | 18.0.1.0       | installed
 project_sms                                | 18.0.1.0       | installed
 project_stock                              | 18.0.1.0       | installed
 project_stock_account                      | 18.0.1.0       | installed
 project_todo                               | 18.0.1.0       | installed
 purchase                                   | 18.0.1.2       | installed
 purchase_edi_ubl_bis3                      | 18.0.1.0       | installed
 purchase_mrp                               | 18.0.1.0       | installed
 purchase_stock                             | 18.0.1.2       | installed
 quality                                    | 18.0.1.0       | installed
 rating                                     | 18.0.1.1       | installed
 resource                                   | 18.0.1.1       | installed
 resource_mail                              | 18.0.1.0       | installed
 sale                                       | 18.0.1.2       | installed
 sale_account_accountant                    | 18.0.1.0       | installed
 sale_async_emails                          | 18.0.1.0       | installed
 sale_crm                                   | 18.0.1.0       | installed
 sale_edi_ubl                               | 18.0.1.0       | installed
 sale_expense                               | 18.0.1.0       | installed
 sale_external_tax                          | 18.0.1.0       | installed
 sale_management                            | 18.0.1.0       | installed
 sale_mrp                                   | 18.0.1.0       | installed
 sale_pdf_quote_builder                     | 18.0.1.0       | installed
 sale_project                               | 18.0.1.0       | installed
 sale_project_stock                         | 18.0.1.0       | installed
 sale_project_stock_account                 | 18.0.1.0       | installed
 sale_purchase                              | 18.0.1.0       | installed
 sale_purchase_project                      | 18.0.1.0       | installed
 sale_purchase_stock                        | 18.0.1.0       | installed
 sale_service                               | 18.0.1.0       | installed
 sale_sms                                   | 18.0.1.0       | installed
 sale_stock                                 | 18.0.1.0       | installed
 sale_timesheet                             | 18.0.1.0       | installed
 sale_timesheet_enterprise                  | 18.0.0.1       | installed
 sales_team                                 | 18.0.1.1       | installed
 sms                                        | 18.0.3.0       | installed
 snailmail                                  | 18.0.0.4       | installed
 snailmail_account                          | 18.0.0.1       | installed
 snailmail_account_followup                 | 18.0.1.0       | installed
 social_media                               | 18.0.0.1       | installed
 spreadsheet                                | 18.0.1.0       | installed
 spreadsheet_account                        | 18.0.1.0       | installed
 spreadsheet_dashboard                      | 18.0.1.0       | installed
 spreadsheet_dashboard_account              | 18.0.1.0       | installed
 spreadsheet_dashboard_account_accountant   | 18.0.1.0       | installed
 spreadsheet_dashboard_crm                  | 18.0.1.0       | installed
 spreadsheet_dashboard_documents            | 18.0.1.0       | installed
 spreadsheet_dashboard_edition              | 18.0.1.0       | installed
 spreadsheet_dashboard_helpdesk             | 18.0.1.0       | installed
 spreadsheet_dashboard_hr_contract          | 18.0.1.0       | installed
 spreadsheet_dashboard_hr_expense           | 18.0.1.0       | installed
 spreadsheet_dashboard_hr_timesheet         | 18.0.1.0       | installed
 spreadsheet_dashboard_marketing_automation | 18.0.1.0       | installed
 spreadsheet_dashboard_mrp_account          | 18.0.1.0       | installed
 spreadsheet_dashboard_purchase_stock       | 18.0.1.0       | installed
 spreadsheet_dashboard_sale                 | 18.0.1.0       | installed
 spreadsheet_dashboard_sale_timesheet       | 18.0.1.0       | installed
 spreadsheet_dashboard_stock                | 18.0.1.0       | installed
 spreadsheet_dashboard_stock_account        | 18.0.1.0       | installed
 spreadsheet_edition                        | 18.0.1.0       | installed
 spreadsheet_sale_management                | 18.0.1.0       | installed
 stock                                      | 18.0.1.1       | installed
 stock_account                              | 18.0.1.1       | installed
 stock_accountant                           | 18.0.1.0       | installed
 stock_barcode                              | 18.0.1.0       | installed
 stock_barcode_mrp                          | 18.0.1.0       | installed
 stock_barcode_picking_batch                | 18.0.1.0       | installed
 stock_enterprise                           | 18.0.1.0       | installed
 stock_fleet                                | 18.0.1.0       | installed
 stock_fleet_enterprise                     | 18.0.1.0       | installed
 stock_picking_batch                        | 18.0.1.0       | installed
 stock_sms                                  | 18.0.1.0       | installed
 studio_customization                       |                | installed
 theme_default                              | 18.0.1.0       | installed
 timer                                      | 18.0.1.0       | installed
 timesheet_grid                             | 18.0.1.0       | installed
 uom                                        | 18.0.1.0       | installed
 utm                                        | 18.0.1.1       | installed
 web                                        | 18.0.1.0       | installed
 web_cohort                                 | 18.0.1.0       | installed
 web_editor                                 | 18.0.1.0       | installed
 web_enterprise                             | 18.0.1.0       | installed
 web_gantt                                  | 18.0.2.0       | installed
 web_grid                                   | 18.0.0.1       | installed
 web_hierarchy                              | 18.0.1.0       | installed
 web_map                                    | 18.0.1.0       | installed
 web_mobile                                 | 18.0.1.0       | installed
 web_studio                                 | 18.0.1.0       | installed
 web_tour                                   | 18.0.1.0       | installed
 web_unsplash                               | 18.0.1.1       | installed
 website                                    | 18.0.1.0       | installed
 website_crm                                | 18.0.2.1       | installed
 website_crm_iap_reveal                     | 18.0.1.1       | installed
 website_crm_iap_reveal_enterprise          | 18.0.1.0       | installed
 website_crm_sms                            | 18.0.1.0       | installed
 website_documents                          | 18.0.1.0       | installed
 website_enterprise                         | 18.0.1.0       | installed
 website_helpdesk                           | 18.0.1.0       | installed
 website_hr_recruitment                     | 18.0.1.1       | installed
 website_links                              | 18.0.1.0       | installed
 website_mail                               | 18.0.0.1       | installed
 website_mass_mailing                       | 18.0.1.0       | installed
 website_payment                            | 18.0.1.0       | installed
 website_project                            | 18.0.1.0       | installed
 website_sms                                | 18.0.1.0       | installed
 website_studio                             | 18.0.1.0       | installed
 whatsapp                                   | 18.0.1.0       | installed
 whatsapp_account                           | 18.0.1.0       | installed
 whatsapp_payment                           | 18.0.1.0       | installed
 whatsapp_sale                              | 18.0.1.0       | installed
(265 rows)

